### ISSUE TITLE
Start GUI with options

### ISSUE THREAD

**Issue by fjflores** [zekebarger/AccuSleep_X#1]
Hi Zeke. 

Thanks for the code. It is working quite well.

I'm just wondering if it  is possible to start the  the GUI with the recordings and options like Fs already loaded, using a script for example.

Best,

**Comment by zekebarger** [comment]
Hi Francisco,

In AccuSleep_GUI_X.m, you can set the default sampling rate by changing the empty string in line 116 to your desired value (like '1000'). The same goes for epoch length, on line 117.

Loading multiple recordings from a single file is more complicated, and is not currently possible with this version of AccuSleep. I did implement something like this for my lab--look for the files with the suffix "DLE" [here](https://github.com/zekebarger/DanLab). This version can load a special type of file that I used to organize all the EEG/EMG recordings from one mouse + treatment condition. This file, unfortunately named a "dirlist", is just a list of directories (folders). The assumption is that each recording, meaning an EEG file + EMG file + label file, is stored in its own directory. You can create a dirlist using the AS_manageLists GUI. The code for that is also in the DanLab repo. But moving the relevant code from AccuSleep DLE to AccuSleep X could be a little tricky and I'm not sure it would outweigh the time savings of loading multiple recordings at once :)

Zeke
